### ISSUE TITLE
Fixing/Finalizing definition of `flexible_joint_state` message

### ISSUE THREAD

**Issue by destogl** [ros-controls/roadmap#13]
Hi,

just a few thoughts on `flexible_joint_state` message before I forget them :)

1. In Meeting on March 25th, Jeremie (@artivis) mentioned in the chat that `flexible` as a word is kinda misleading since it suggests that this message is something about soft robotics. What do you think about that?
    * `general` or `adjustable` could also be the right words?

2. We should document in the design document the most applicable keys for value identifiers.

3. There is an issue, who can define and change the `value_identifier` list on runtime. I propose that this is manged only and only by RobotHW. But then we could lose the flexibility of communication between controllers.
    * Do we need somehow to distinguish which `value_identifiers` are defined by `RobotHardware` and which one is defined by controllers? Who should take care of that? Controller manager?

4. How should hardware and controllers access the message? There are some comments on that in the [Realtime Access Control](../blob/master/design_drafts/flexible_joint_states_msg.md#realtime-access-control) section. It is still not clear to me if there should be one instance for `RobotHardware` and Controllers, which is than copied by the Execution manager, or should there be only one instance.

**Comment by bmagyar** [comment]
Moving comments of @matthew-reynolds here with adjusted numbering

Couple other notes:

5. Line 59 is a bit convoluted - It actually took me a couple of reads through that sentence to understand. Perhaps it could be simplified to something along the lines of "The new proposal reflects a map-like datatype, where each interface contains a dynamic set of value identifiers and values. By contrast, the sensor_msgs/JointState contains a static set of 3 value identifiers." Thoughts?

6. As mentioned in the working group meeting, "flexible" might not be the best name, since the term "flexible" in robotics is sometimes used interchangeably with "soft" robots, ie robots with non-rigid bodies. Not sure what the best alternative is though. --> Point 1 above

**Comment by mateus-amarante** [comment]
Name suggestions: `generic_joint_state`, `universal_joint_state`, `composite_joint_state`, and `multi_interface_joint_state`.

**Comment by destogl** [comment]
@bmagyar: could we address these questions?

Here the update:
1. #16 and #17 
2. I addressed this in  ros-controls/control_msgs#44
6. same as 1.

Still 3, 4 and 5 to go.
